name: Test

on:
    pull_request:
        paths:
            - src
            - package.json
            - .babelrc.js
            - jest.config.ts
            - tsconfig.build.json
            - tsconfig.json
        types:
            - opened
            - reopened
            - synchronize

    push:
        paths:
            - src
            - package.json
            - .babelrc.js
            - jest.config.ts
            - tsconfig.build.json
            - tsconfig.json

jobs:
    test:
        runs-on: ubuntu-latest
        environment: test
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'
                registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: npm install

            - name: Test
              run: npm run test