name: Unpublish

on:
    release:
        types:
            - deleted

jobs:
    unpublish:
        runs-on: ubuntu-latest
        environment: publish
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Set up Node.js
            uses: actions/setup-node@v4
            with:
                node-version: 20
                registry-url: 'https://registry.npmjs.org'

          - name: Delete package version
            env:
                NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
            run: |
                PACKAGE_NAME=$(npm pkg get name | sed -e 's/^"//' -e 's/"$//')
                PACKAGE_VERSION=$(npm pkg get version | sed -e 's/^"//' -e 's/"$//')
                npm unpublish $PACKAGE_NAME@$PACKAGE_VERSION --force
